; ==========================================
; [PART 1] WinRun4J 실행 설정
; ==========================================
main.class=com.example.facesec.FaceSecApp
service.id=FaceSecApp
service.name=Face Security App
service.description=Face Recognition Security Application

;working.directory=.

classpath.1=face.jar
vm.location=jre\bin\server\jvm.dll

; [VM 메모리 및 네트워크 설정]
vmarg.1=-Xms64m
vmarg.2=-Xmx1024m
vmarg.3=-Dsun.java2d.opengl=true
; IPv4 강제 사용 (통신 에러 해결용)
vmarg.4=-Djava.net.preferIPv4Stack=true

; ==========================================
; [PART 2] 사용자 설정
; ==========================================

[SETUP]
; 다이얼로그 좌표/크기
win=0,0,1280,1024

; 프리뷰 프레임 크기(카메라 요청 해상도)
frame_size=800,600

; 다이얼로그 내 카메라 화면 위치 및 크기 (x, y, width, height)
; preview_rect = X(무시됨), Y(적용됨), Width, Height
preview_rect=400,100,600,600

; 매칭 임계값(LBPH distance)
MATCH_THRESHOLD=0.7

; FaceSecApp TCP 클라이언트 설정
;ip=192.168.100.125
;ip=localhost
ip=127.0.0.1

;통신 포트 번호
port=5001

; --- 자동 캡처 설정 (거리 제한) ---
; [변경] 최소 크기 (이것보다 작으면 '너무 멀다' 판단)
min_capture_ratio=0.27

; [신규] 최대 크기 (이것보다 크면 '너무 가깝다' 판단)
max_capture_ratio=0.33

; 자동 캡처 재트리거 최소 간격(ms, 500~60000). 기본 3000
auto_capture_cooldown_ms=2000

; 카운트다운 길이(초, 1~10). 기본 3
auto_capture_countdown_sec=1

; --- 보안 캡처 설정 (신규/중요) ---
; true = 자동 보안 캡처 ON, false = OFF
security_capture_enabled=true

;보안캡쳐 경로 설정(값 없을 경우 실행파일 위치에)
;security_path=C:/MyFaceSec/Captures

; 키보드/F1~F3/TCP 명령 등 “입력 발생” 시 보안 캡처 할지 여부
; true = 입력 있을 때도 1장 찍음
security_capture_on_input=true

; security_captures 폴더에 최대 몇 장까지 유지할지
; 넘으면 오래된 파일부터 자동 삭제
security_capture_max_files=1000

; 보안 캡처 이미지 포맷 (jpg 또는 png)
security_capture_format=jpg
